projectManagementName: Project Management

projectManagementStatusStart: To describe

userStoryLabel: User story

bugLabel: Bug

taskLabel: Task

TechnicalStoryLabel: Technical story

cardTypeFieldName: Type