projectManagementName: Project Management

projectDevelopmentName: Project Development

projectManagementStatusStart: To describe

userStoryLabel: User story

bugLabel: Bug

taskLabel: Task

TechnicalStoryLabel: Technical story

cardTypeFieldName: Type

cardReviewStatusFieldName: Review status

cardManagementReviewStatusStart: Todo

cardDevelopmentReviewStatusFieldName: Waiting