name: Create branch and draft

on:
  workflow_dispatch:
    inputs:
      baseBranch:
        description: 'Base branch'
        required: true
        default: 'dev'
        type: string
      headBranch:
        description: 'Head branch'
        required: true
        type: string
      prTitle:
        description: 'Pull request title'
        required: true
        type: string
      issueNumber:
        description: 'Issue number'
        required: true
        type: number

jobs:
  create-branch-and-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check if branch exists
        id: check-branch-exists
        continue-on-error: true
        run: |
          git fetch --all
          (git branch --list ${{ github.event.inputs.headBranch }} && echo "branchExists=true" && echo "Branch already exists") || echo "branchExists=false"


      - name: Create branch
        id: create-branch
        # if branch does not exist, create it
        if: steps.check-branch-exists.outputs.branchExists == 'false'
        run: |
          git checkout -b ${{ github.event.inputs.headBranch }}
          git config --global user.email "ci@astrodevslabs.io" && git config --global user.name "Astrodevs CI"
          git commit --allow-empty -m "chore: create branch ${{ github.event.inputs.headBranch }}"
          git push origin ${{ github.event.inputs.headBranch }}

      - name: Check if PR exists
        id: check-pr-exists
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git fetch --all
          git checkout ${{ github.event.inputs.headBranch }}
          (gh pr view --json number --jq '.number' && echo "prExists=true" >> $GITHUB_OUTPUT) || echo "prExists=false" >> $GITHUB_OUTPUT

      - name: Create pull request
        if: steps.check-pr-exists.outputs.prExists == 'false'
        env:
          GH_TOKEN: ${{ secrets.ADMIN_PAT}}
        run: |
          gh pr create --title "${{ github.event.inputs.prTitle }}" --body "Solves #${{ github.event.inputs.baseBranch }} --head ${{github.event.inputs.headBranch }} --repo ${{ github.event.repository.full_name }} --draft

