on:
  issues:
    types: [opened, labeled]

jobs:
  create-project-card:
    # if issue is opened and has label "User Story", "Bug", "Task" or "Technical Story"
    if: github.event.action == 'opened' && (contains(github.event.issue.labels.*.name, 'User Story') || contains(github.event.issue.labels.*.name, 'Bug') || contains(github.event.issue.labels.*.name, 'Task') || contains(github.event.issue.labels.*.name, 'Technical Story'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create project card
        uses: actions/github-script@v6
        with:
          script: |
            const query = `
              query($organization: String!) {
                organization(login: $organization) {
                  projectsV2(first: 10) {
                    nodes {
                      id
                      title
                    }
                  }
                }
              }
            `
            const variables = {
              organization: context.repo.owner
            }

            const projects = await github.graphql(query, variables)
            const project = projects.organization.projectsV2.nodes.find(project => project.title === 'Project Management')
            if (!project) {
              throw new Error('Project Management project not found')
            }
            console.log(project)

            const createMutation = `
              mutation($input: AddProjectV2ItemByIdInput!) {
                addProjectV2ItemById(input: $input) {
                  item {
                    id
                    fieldValues(first: 10) {
                      nodes {
                        ... on ProjectV2ItemFieldIterationValue {
                          id
                          title
                          startDate
                          iterationId
                          duration
                        }
                        ... on ProjectV2ItemFieldLabelValue {
                          labels(first: 20) {
                            nodes {
                              name
                              id
                            }
                          }
                        }
                        ... on ProjectV2ItemFieldNumberValue {
                          number
                          id
                          field {
                            ... on ProjectV2Field {
                              name
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }`

            const createVariables = {
              input: {
                projectId: project.id,
                contentId: context.payload.issue.node_id
              }
            }

            const result = await github.graphql(createMutation, createVariables)
            console.log(result)
          github-token: ${{ secrets.ADMIN_PAT }}


      #- name: Translate label to custom field
      #  uses: actions/github-script@v6
      #  with:
      #    script: |
      #      const typeFieldId = 40615192;
      #      github.projects.listForRepo({
      #        owner: context.repo.owner,
      #        repo: context.repo.repo
      #      }).then(projects => {
      #        const project = projects.data.find(project => project.name === 'Project Management')
      #        github.projects.listColumns({
      #          project_id: project.id
      #        }).then(columns => {
      #          const column = columns.data.find(column => column.name === 'To describe')
      #          github.projects.listCards({
      #            column_id: column.id
      #          }).then(cards => {
      #            const card = cards.data.find(card => card.content_url === context.payload.issue.url)
      #            github.projects.updateCard({
      #              card_id: card.id,
      #              column_id: column.id,
      #              custom_field_id: typeFieldId,
      #              value_id: 6320a3d5
      #            })
      #          })
      #        })
      #      })
            
      
