on:
  issues:
    types: [assigned]


jobs:
  create-branch-and-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find branch name
        id: find-branch-name
        uses: actions/github-script@v3
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          TITLE: ${{ github.event.issue.title }}
          IS_USER_STORY: ${{ contains(github.event.issue.labels.*.name, vars.PROJECT_TYPE_USER_STORY) }}
          IS_BUG: ${{ contains(github.event.issue.labels.*.name, vars.PROJECT_TYPE_BUG) }}
          IS_TASK: ${{ contains(github.event.issue.labels.*.name, vars.PROJECT_TYPE_TASK) }}
          IS_TECHNICAL_STORY: ${{ contains(github.event.issue.labels.*.name, vars.PROJECT_TYPE_TECHNICAL_STORY) }}
          BRANCH_USER_STORY_PREFIX: ${{ vars.BRANCH_USER_STORY_PREFIX }}
          BRANCH_BUG_PREFIX: ${{ vars.BRANCH_BUG_PREFIX }}
          BRANCH_TECHNICAL_STORY_PREFIX: ${{ vars.BRANCH_TECHNICAL_STORY_PREFIX }}
          PROJECT_TYPE_USER_STORY: ${{ vars.PROJECT_TYPE_USER_STORY }}
          PROJECT_TYPE_BUG: ${{ vars.PROJECT_TYPE_BUG }}
          PROJECT_TYPE_TECHNICAL_STORY: ${{ vars.PROJECT_TYPE_TECHNICAL_STORY }}
        with:
          #github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let branchName = ''
            const isUserStory = JSON.parse(process.env.IS_USER_STORY)
            const isBug = JSON.parse(process.env.IS_BUG)
            const isTask = JSON.parse(process.env.IS_TASK)
            const isTechnicalStory = JSON.parse(process.env.IS_TECHNICAL_STORY)
            const sanitizedTitle = process.env.TITLE.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()

            if (isUserStory && !isTechnicalStory)
              branchName = `${process.env.BRANCH_USER_STORY_PREFIX}/${sanitizedTitle}`
            else if (isBug)
              branchName = `${process.env.BRANCH_BUG_PREFIX}/${sanitizedTitle}`
            else if (isTechnicalStory)
              branchName = `${process.env.BRANCH_TECHNICAL_STORY_PREFIX}/${sanitizedTitle}`

            if (!isTask && (isUserStory || isBug || isTechnicalStory)) {
              console.log(`Branch name: ${branchName}`)
              return { 
                branchName: branchName.replace(/--/g, '-'),
                baseBranch: 'dev', 
              }
            }

            const query = `query Nodes($number: Int!, $repo: String!, $organization: String!) {
              organization(login: $organization) {
                repository(name: $repo) {
                  issue(number: $number) {
                    trackedInIssues(first: 1) {
                      nodes {
                        title
                        labels(first: 20) {
                          nodes {
                            name
                          }
                        }
                        trackedInIssues(first: 1) {
                          nodes {
                            title
                            labels(first: 20) {
                              nodes {
                                name
                              }
                            }
                            trackedInIssues(first: 1) {
                              nodes {
                                title
                                labels(first: 20) {
                                  nodes {
                                    name
                                  }
                                }
                                trackedInIssues(first: 1) {
                                  nodes {
                                    title
                                    labels(first: 20) {
                                      nodes {
                                        name
                                      }
                                    }
                                    trackedInIssues(first: 1) {
                                      nodes {
                                        title
                                        labels(first: 20) {
                                          nodes {
                                            name
                                          }
                                        }
                                        trackedInIssues(first: 1) {
                                          nodes {
                                            title
                                            labels(first: 20) {
                                              nodes {
                                                name
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }`

            const variables = {
              number: parseInt(process.env.ISSUE_NUMBER),
              repo: context.repo.repo,
              organization: context.repo.owner
            }

            const result = await github.graphql(query, variables)
            let node = result.organization.repository.issue.trackedInIssues.nodes[0]
            const nodes = [node.title]
            for (; node.trackedInIssues.nodes.length > 0; node = node.trackedInIssues.nodes[0]) {
              console.log(node)
              nodes.push(node.title)
            }
            console.log("end node", node)
            console.log("labels", node.labels.nodes)
            const isRootUserStory = node.labels.nodes.some(label => label.name === process.env.PROJECT_TYPE_USER_STORY)
            const isRootBug = node.labels.nodes.some(label => label.name === process.env.PROJECT_TYPE_BUG)
            const isRootTechnicalStory = node.labels.nodes.some(label => label.name === process.env.PROJECT_TYPE_TECHNICAL_STORY)

            const sanitizedNodes = nodes.map(node => {
              const lowered = node.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase().replace(/--/g, '-')
              return lowered.charAt(0).toUpperCase() + lowered.slice(1)
            })

            let baseBranch = 'dev'

            if (isRootUserStory && !isRootTechnicalStory) {
              branchName = `${process.env.BRANCH_USER_STORY_PREFIX}/${sanitizedNodes.reverse().join('/')}/${sanitizedTitle}`
              baseBranch = `${process.env.BRANCH_USER_STORY_PREFIX}/${sanitizedNodes.reverse().join('/').toLowerCase()}`
            } else if (isRootBug) {
              branchName = `${process.env.BRANCH_BUG_PREFIX}/${sanitizedNodes.reverse().join('/')}/${sanitizedTitle}`
              baseBranch = `${process.env.BRANCH_BUG_PREFIX}/${sanitizedNodes.reverse().join('/').toLowerCase()}`
            } else if (isRootTechnicalStory) {
              branchName = `${process.env.BRANCH_TECHNICAL_STORY_PREFIX}/${sanitizedNodes.reverse().join('/')}/${sanitizedTitle}`
              baseBranch = `${process.env.BRANCH_TECHNICAL_STORY_PREFIX}/${sanitizedNodes.reverse().join('/').toLowerCase()}`
            } else
              branchName = `${sanitizedNodes.reverse().join('/')}/${sanitizedTitle}`
            
            console.log(`Branch name: ${branchName}`)
            return { branchName, baseBranch }

      - name: Check if branch exists
        id: check-branch-exists
        continue-on-error: true
        run: |
          git fetch --all
          git branch --list ${{ fromJson(steps.find-branch-name.outputs.result).branchName }}
          echo "Branch already exists"
          echo "{branchExists}={true}" >> $GITHUB_OUTPUT


      - name: Create branch
        id: create-branch
        # if branch does not exist, create it
        if: steps.check-branch-exists.outputs.branchExists == 'false'
        run: |
          git checkout -b ${{ fromJson(steps.find-branch-name.outputs.result).branchName }}
          git config --global user.email "ci@astrodevslabs.io" && git config --global user.name "Astrodevs CI"
          git commit --allow-empty -m "chore: create branch ${{ fromJson(steps.find-branch-name.outputs.result).branchName }}"
          git push origin ${{ fromJson(steps.find-branch-name.outputs.result).branchName }}

      - name: Check if PR exists
        id: check-pr-exists
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git fetch --all
          git checkout ${{ fromJson(steps.find-branch-name.outputs.result).branchName }}
          (gh pr view --json number --jq '.number' && echo "{prExists}={true}" >> $GITHUB_OUTPUT) || echo "{prExists}={false}" >> $GITHUB_OUTPUT
        
      - name: debug
        run: |
          echo ${{ steps.check-pr-exists.outputs.prExists }}

      - name: Create pull request
        if: steps.check-pr-exists.outputs.prExists == 'false'
        env:
          GH_TOKEN: ${{ secrets.ADMIN_PAT}}
        run: |
          gh pr create --title "${{ github.event.issue.title }}" --body "Solves #${{github.event.issue.number}}" --base ${{ fromJson(steps.find-branch-name.outputs.result).baseBranch }} --head ${{ fromJson(steps.find-branch-name.outputs.result).branchName }} --repo ${{ github.event.repository.full_name }} --draft



